### ISSUE TITLE
Adding an option to delay starting async threads

### ISSUE THREAD

**Issue by bheads** [etcimon/libasync#21]
I am using libasync with daemonize (https://github.com/NCrashed/daemonize).  Daemonize forks the process which is resulting in the GC to deadlock.

I tested locally with delaying starting the threads and I am no longer getting the GC deadlock.

**Comment by etcimon** [comment]
Oh, I see. What are you using to delay it?

**Comment by bheads** [comment]
Updated threads.d

shared static this() {
        gs_wlock = new Mutex;
        gs_threads = new ThreadGroup;
        gs_started = new Condition(gs_wlock);
}

void spawnAsyncThreads() {
        foreach (i; 0 .. 4) {
                Thread thr = new CmdProcessor;
                gs_threads.add(thr);
                thr.isDaemon = true;
                thr.name = "CmdProcessor";
                thr.start();
                core.atomic.atomicOp!"+="(gs_threadCnt, cast(int) 1);
                synchronized(gs_wlock)
                        gs_started.wait(1.seconds);
        }
}


I just call spawnAsyncThreads after I fork.  Not the safest code be does prevent the deadlock.

I was thinking of added a version tag to enable this behavior

**Comment by etcimon** [comment]
Actually, I think it might be better to let users manually call it, and to add assertions where needed to check if it was called.

**Comment by bheads** [comment]
I will start on a PR.  I was thinking of asserting when you run the event loop, and using gs_threadCnt as the check (make sure there is at least one CmdProcessor thread running). 

If you have any other insights/ideas...

**Comment by bheads** [comment]
was thinking of using the double check with a sync block idomion

```
void spawnAsyncThreads() {
	if(core.atomic.atomicLoad(gs_threadCnt) == 0) {
		synchronized {
			if(core.atomic.atomicLoad(gs_threadCnt) == 0) {
				foreach (i; 0 .. 4) {
					Thread thr = new CmdProcessor;
					gs_threads.add(thr);
					thr.isDaemon = true;
					thr.name = "CmdProcessor";
					thr.start();
					core.atomic.atomicOp!"+="(gs_threadCnt, cast(int) 1);	
					synchronized(gs_wlock)
						gs_started.wait(1.seconds);
				}
			}
		}
	}
}
```

Then I was thinking the call to EventLoop loop could call spawnAsyncThreads.  Would set a flag in the EventLoop to only do it once since this requires at least one atomicLoad

**Comment by MartinNowak** [comment]
2.067 will come with initOnce btw.
http://dlang.org/phobos-prerelease/std_concurrency.html#.initOnce
