### ISSUE TITLE
Tag new release with version based dependencies

### ISSUE THREAD

**Issue by s-ludwig** [etcimon/libasync#25]
The latest 0.7.0 version still uses a `~master` dependency to memutils. It would be nice to have a versioned dependency included in the upcoming 0.7.23 release of vibe.d. Can you make a quick tag (assuming that things are stable enough) and possibly quickly test on DMD 2.067-rc.1 in advance?

**Comment by etcimon** [comment]
I've added R/W access to the repositories currently involved as vibe.d dependencies. It's mostly your code tweaked and put together differently anyways.
