### ISSUE TITLE
[libasync 0.7.2][DMD 2.067][OS X 10.10] Compilation fails

### ISSUE THREAD

**Issue by kozlice** [etcimon/libasync#29]
Hello,

I've added libasync via dub to my sandbox project and got this on `dun run libasync`:

    ../../.dub/packages/libasync-0.7.2/source/libasync/posix.d(2669): Error: module libasync.internals.socket_compat import 'sockaddr_in' not found
    ../../.dub/packages/libasync-0.7.2/source/libasync/posix.d(2669): Error: module libasync.internals.socket_compat import 'sockaddr_in6' not found

I took a look at `socket_compat` submodule, and there are no definitions of `sockaddr_in`/`sockaddr_in6` structures. Importing them from `core.sys.posix.netinet.in_` instead helped, but a whole pack of other errors came after that:

	../../.dub/packages/libasync-0.7.2/source/libasync/posix2.d(11): Error: module libasync.internals.socket_compat import 'IPPROTO_TCP' not found
	../../.dub/packages/libasync-0.7.2/source/libasync/posix.d(572): Error: undefined identifier IPPROTO_TCP
	../../.dub/packages/libasync-0.7.2/source/libasync/posix.d(572): Error: undefined identifier TCP_NODELAY
	../../.dub/packages/libasync-0.7.2/source/libasync/posix2.d(30): Error: template instance libasync.posix.EventLoopImpl.setOption!bool error instantiating
	../../.dub/packages/libasync-0.7.2/source/libasync/posix2.d(54): Error: module libasync.internals.socket_compat import 'IPPROTO_TCP' not found
	../../.dub/packages/libasync-0.7.2/source/libasync/posix2.d(110): Error: module libasync.internals.socket_compat import 'IPPROTO_UDP' not found
	../../.dub/packages/libasync-0.7.2/source/libasync/posix.d(1438): Error: module libasync.internals.socket_compat import 'addrinfo' not found
	../../.dub/packages/libasync-0.7.2/source/libasync/posix.d(1438): Error: module libasync.internals.socket_compat import 'AI_NUMERICHOST' not found
	../../.dub/packages/libasync-0.7.2/source/libasync/posix.d(1438): Error: module libasync.internals.socket_compat import 'AI_NUMERICSERV' not found
	../../.dub/packages/libasync-0.7.2/source/libasync/posix.d(1452): Error: module libasync.internals.socket_compat import 'addrinfo' not found
	../../.dub/packages/libasync-0.7.2/source/libasync/tcp.d(57): Error: template instance libasync.events.EventLoop.setOption!bool error instantiating
	../../.dub/packages/libasync-0.7.2/source/libasync/tcp.d(50):        instantiated from here: setOption!bool
	FAIL ../../.dub/packages/libasync-0.7.2/.dub/build/library-debug-posix.osx-x86_64-dmd_2067-61F4E891DFD3D00EA7E7729A17EAC622/ async staticLibrary

**Comment by etcimon** [comment]
Hi there,

try an `import core.sys.posix.netinet.in_;` at the top of posix.d, my test platform isn't working right now could you let me know if it works? Thanks!

**Comment by etcimon** [comment]
Oh nevermind I just saw you did it, I'll fix my test platform and push a fix

**Comment by etcimon** [comment]
Let me know if it works for you now https://github.com/etcimon/libasync/commit/6e466895806ec09967a5b1ba73451781e6b3b7e9

**Comment by kozlice** [comment]
Thanks for the fast fix! It works now, I've got example TCP server running
