### ISSUE TITLE
Connection Closed with curl

### ISSUE THREAD

**Issue by yannick** [etcimon/libasync#31]
not sure if this is a bug, but when i do calls to vibe.d/libasync with curl i usually get an exception.
doesn't happen if i use a browser.

```
object.Exception@../.dub/packages/vibe-d-0.7.23/source/vibe/core/drivers/libasync.d(1267): Connection closed
----------------
./test-vibe-threads(void vibe.core.core.VibeDriverCore.yieldForEvent()+0x63) [0x7ca643]
./test-vibe-threads(bool vibe.core.drivers.libasync.LibasyncTCPConnection.waitForData(core.time.Duration)+0x16d) [0x7d3285]
./test-vibe-threads(void vibe.http.server.handleHTTPConnection(vibe.core.net.TCPConnection, vibe.http.server.HTTPServerListener)+0x1eb) [0x86a457]
./test-vibe-threads(void vibe.http.server.listenHTTPPlain(vibe.http.server.HTTPServerSettings).doListen(vibe.http.server.HTTPServerSettings, ulong, immutable(char)[]).__lambda4(vibe.core.net.TCPConnection)+0x62) [0x869df2]
./test-vibe-threads(void vibe.core.drivers.libasync.LibasyncTCPConnection.onConnect()+0x7e) [0x7d482e]
./test-vibe-threads(void vibe.core.core.makeTaskFuncInfo!(void delegate()).makeTaskFuncInfo(ref void delegate()).callDelegate(vibe.core.core.TaskFuncInfo*)+0x72) [0x7cbd4e]
./test-vibe-threads(void vibe.core.core.CoreTask.run()+0x12e) [0x7c9a8e]
./test-vibe-threads(void core.thread.Fiber.run()+0x2a) [0x9585d2]
./test-vibe-threads(fiber_entryPoint+0x61) [0x9584c1]
[(nil)]
Task terminated with uncaught exception: Connection closed

```

**Comment by etcimon** [comment]
This means curl closed the connection abruptly first while the server was expecting a keep-alive timeout to be respected. I think this could be caught as a special case and silenced unless you tell me that there was loss of data

**Comment by yannick** [comment]
nope the payload data arrived just fine.

**Comment by etcimon** [comment]
I currently use this branch for vibe.d: https://github.com/etcimon/vibe.d/tree/http2-botan-dev

I have a new exception type and new handlers in there, they silence the remote connection closure
https://github.com/etcimon/vibe.d/blob/http2-botan-dev/source/vibe/core/core.d#L976

**Comment by s-ludwig** [comment]
@etcimon: This is not the right way to fix it. The exception shouldn't occur in the first place (`waitForData` should return `false` instead of throwing when the remote closes the connection). I didn't have time to look for the root cause, though.

**Comment by etcimon** [comment]
Hmm, the onClose event resumes with an exception maybe I could add a flag instead when its waiting for data

**Comment by etcimon** [comment]
Well it looks like my code in the http2-botan-dev branch had gone stable only when paired with a throwing `waitForData`. I'll have to go through the debug process again :/

**Comment by s-ludwig** [comment]
That would be good. Better than throwing and immediately catching the exception.

**Comment by s-ludwig** [comment]
(Previous reply was made on an outdated browser page, didn't notice your last comment)

**Comment by etcimon** [comment]
Yes, I'm finished with the changes and they're now available here: https://github.com/rejectedsoftware/vibe.d/pull/1121
