### ISSUE TITLE
file descriptor leak when TCP connection aborted by timer (patch)

### ISSUE THREAD

**Issue by ikod** [etcimon/libasync#33]
ubuntu 14.04
libasync commit ae7a020bfb466cb202933d99e73b411bc49b9eaf
```
import libasync;
import std.socket;
import std.stdio;
import core.memory;
import std.experimental.logger;

void main() {
    void handler(TCPEvent ev) {
        writeln("Event ", ev);
    }
    globalLogLevel(LogLevel.trace);
    auto evl = new EventLoop();
    auto count = 1000;
    foreach(_;0 .. count) {
        auto conn = new AsyncTCPConnection(evl);
        conn.host("1.1.1.1", 9999).run(&handler);
        auto timer = new AsyncTimer(evl);
        timer.duration = 10.msecs;
        timer.run({
            trace("timeout");
        });
        evl.loop(100.seconds);
        conn.kill(true);
        timer.kill();
        trace("loop done");
        destroy(conn);
        destroy(timer);
        GC.collect();
        GC.minimize();
    }
    writeln("done");
    destroyAsyncThreads();
}
```
This code try to implement tcp client connection with fixed timeout: timer started, connection started (to unreachable node). Uncompleted connection killed after timer expire. Problem: file descriptor leaks.

#### At the start of the log shows FD#6, FD#15 and so on:
Resolving 1.1.1.1:9999
Connection **FD#6** added to 3
Backtrace: connect
 | Status:  ASYNC
 | Error: EINPROGRESS
 | Message: Operation now in progress
Got 1 event(s)
Event 0 of: 128
Got timer! 15
Kill socket
Resolving 1.1.1.1:9999
Connection **FD#15** added to 3
Backtrace: connect
 | Status:  ASYNC
 | Error: EINPROGRESS
 | Message: Operation now in progress
Got 1 event(s)
Event 0 of: 128
Got timer! 16
Kill socket
Resolving 1.1.1.1:9999
Connection **FD#16** added to 3
Backtrace: connect
 | Status:  ASYNC
 | Error: EINPROGRESS
 | Message: Operation now in progress
Got 1 event(s)

#### At the end of the run:
Resolving 1.1.1.1:9999
Connection **FD#1011** added to 3
Backtrace: connect
 | Status:  ASYNC
 | Error: EINPROGRESS
 | Message: Operation now in progress
Got 1 event(s)
Event 0 of: 128
Got timer! 1012
Kill socket
Resolving 1.1.1.1:9999
Connection **FD#1012** added to 3
Backtrace: connect
 | Status:  ASYNC
 | Error: EINPROGRESS
 | Message: Operation now in progress
Got 1 event(s)
Event 0 of: 128
Got timer! 1013
Kill socket
done

#### after patch, at the end:
Resolving 1.1.1.1:9999
Connection **FD#5** added to 3
Backtrace: connect
 | Status:  ASYNC
 | Error: EINPROGRESS
 | Message: Operation now in progress
Got 1 event(s)
Event 0 of: 128
Got timer! 6
Kill socket
closeSocket
shutdown
close
done

patch (I didn't run any other tests):
```
diff --git a/source/libasync/posix2.d b/source/libasync/posix2.d
index 4004092..b7c1115 100644
--- a/source/libasync/posix2.d
+++ b/source/libasync/posix2.d
@@ -494,6 +494,9 @@ mixin template RunKill()
                                try FreeListObjectAlloc!AsyncTCPConnection.free(ctxt);
                                catch { assert(false, "Failed to free resources"); }
                        }
+            if ( fd != fd_t.init ) {
+                closeSocket(fd, true, forced);
+            }
                        return true;
                }
        }
```

**Comment by etcimon** [comment]
Thanks for your help (again) :)

**Comment by ikod** [comment]
huge thanks for fast fixes!
