### ISSUE TITLE
How to use multiple threads

### ISSUE THREAD

**Issue by donglei** [etcimon/libasync#37]
How to use multiple threads with libasync, could you give an example?
Expect to fork some of the working threads when the main thread is started. The jobs will be processed by the working threads;

**Comment by etcimon** [comment]
Hi donglei,

I thought about writing an example for this using `AsyncSignal`, it should be straightforward but I'm not sure yet what it should cover.

The typical implementation would be triggered by an HTTP request, which is at a much higher level.

```D
shared AsyncSignal gs_sigqueue;
__gshared Mutex gs_mtx;
__gshared Variant[] gs_queue;
shared static this() { mtx = new Mutex; }
void queueHandler() { 
	synchronized(gs_mtx) {
		foreach (item; gs_queue)
			handleItem(item);
	}
}
// This is a thread-safe function that will send a task to the worker
void enqueue(MyObj item) {
	synchronized(gs_mtx) gs_queue ~= Variant(item);
	gs_sigqueue.trigger();
}
void main() {
	// The below handler will be handled by the current thread.
	// to register workers, create the AsyncSignal from another thread.
	gs_sigqueue = new shared AsyncSignal(getThreadEventLoop());
	gs_sigqueue.run(toDelegate(&queueHandler)); //std.functional

	while(getThreadEventLoop().loop()) continue;
}
```

In this example, you can call enqueue from any thread and the item will be handled by the main thread. Do you have a specific protocol that should enqueue items?

**Comment by donglei** [comment]
Thank you for your example. I  have a web project written in D, in order to improve the performance and ability to handle, I intend to use multi thread.The main thread only receives the request, distributed it to the working threads.

**Comment by etcimon** [comment]
If you are using Linux, you can run the same AsyncTCPListener from multiple threads and the requests will be distributed round robin

**Comment by yannick** [comment]
@donglei  for your specific need you don't need multi thread, it would be actually bad. Linux can do the connection sharding for you with SO_REUSEPORT ( https://lwn.net/Articles/542629/ ).
you do not want to have the synchronization overhead within the web framework as long as the clients do not need to communicate together. 
thus the solution you are most probably looking for is fairly simple: just compile with libasync and start the binary multiple times. it will "magically" distribute your load :)

**Comment by Soaku** [comment]
> If you are using Linux, you can run the same AsyncTCPListener from multiple threads and the requests will be distributed round robin

@etcimon I tried doing this, and it worked, but I only a fraction of connections succeeded. The rest seems to get stuck, taking an eternity to connect. 

```
void main() {

    // Spawn 3 listener threads
    foreach (i; 0..3) {

        spawn(&startListener);

    }

}

void startListener() {

    auto eventLoop = getThreadEventLoop;
    auto listener = new AsyncTCPListener(eventLoop);

    listener.host("127.0.0.1", 5483)
            .run(connection => &(new Handler(connection).handle));

    while (!shouldClose) {

        eventLoop.loop();

    }

}
```

**Comment by Soaku** [comment]
Also, would it be possible to just have a single listener and manually move handlers between threads? Would be more efficient in my case.
