### ISSUE TITLE
g_idxAvailable in windows.d would abnormal append 

### ISSUE THREAD

**Issue by mzfhhhh** [etcimon/libasync#51]
i print the g_idxAvailable in windows.d line 2035 and then run this simple code.
```D
auto tm = new AsyncTimer(g_evl);
	tm.duration(1.seconds).run({
	writeln("1");	 
 	tm.rearm(1.seconds);	   
});

auto tm2 = new AsyncTimer(g_evl);
tm2.duration(1.seconds).run({
	writeln("2");
 	tm2.rearm(1.seconds);		   
});
```
g_idxAvailable output:
,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,30,30,30,30,
30,30,30,30,30,30,30,30,........

**Comment by etcimon** [comment]
Thanks for reporting this, that was actually a pretty important bug that I had been looking for. Fix is in master
