### ISSUE TITLE
[feature request] Unix sockets

### ISSUE THREAD

**Issue by Calrama** [etcimon/libasync#54]
I would really like to use libasync for IPC on Linux (specifically I would like to support it in [i3ipc-d](https://github.com/calrama/i3ipc-d) as the event dispatcher), but that does require support for unix sockets. Would it be possible to get support for those in libasync?

**Comment by etcimon** [comment]
Of course, will add within a month or so (once I have time!)

**Comment by Calrama** [comment]
Would it be possible for you give me an overview on what would need to be implemented?
Since I really need this for a project of mine (for which I wrote i3ipc-d in the first place), I tried to judge whether I would be able to implement this myself, but duplicating [the tcp implementation](https://github.com/etcimon/libasync/blob/master/source/libasync/tcp.d) and modifying it for unix did not appear to me to be very straight forward, as `egrep -r` revealed extensive references to `tcp`, i.e. even if I implemented unix.d, I cant easily make out how to plug in into the rest of libasync.

**Comment by etcimon** [comment]
That'll be a pre-initialized file descriptor, you could probably do it by passing a custom fd to `AsyncTCPConnection` but I think `AsyncEvent` would be more of a fit for it. You'd need to create the unix socket beforehand using c-style examples. http://troydhanson.github.io/network/Unix_domain_sockets.html

**Comment by Calrama** [comment]
Okay, thank you for the pointers, I'll try may hand at it.

**Comment by Calrama** [comment]
First attempt of it is [here](https://github.com/Calrama/libasync/commit/3c6f26614bb50637cb2b1985474a66cf0e61650d), though I did have to rewrite some parts of AsyncEvent to support stateful sockets (I need connect and close events to be dispatched for unix domain sockets, but AsyncEvent did not support that yet): There is new argument in the constructor with which the caller tells AsyncEvent whether the given file descriptor is a stateful socket (like UDS) or not.

**Comment by etcimon** [comment]
Looks good so far, it seems to fit in nicely with the rest. Does this work in your tests?

**Comment by Calrama** [comment]
Cool, I was concerned that you may object to changing AsyncEvent like that.
Regarding to your questio: I'm currently using a minimal test like this:

```d
auto loop = getThreadEventLoop;

auto unix = new AsyncUDSConnection(loop);
unix.peer = new UnixAddress("/var/run/user/1000/i3/ipc-socket.1234");
unix.run((code) {
	writeln(code);
});

while (true) {
	loop.loop(-1.seconds);
}
``` 

and the connect/read/close events seem to be dispatched correctly. I'll follow up with a more complete test soon.

**Comment by Calrama** [comment]
https://github.com/Calrama/libasync/commit/f756d97e74daff281ef1c126fdade80f42d91025 seems to be working as expected (complete UDS connection). Up next are a UDS listener, the promised test as an example (using both) and then making sure that this doesn't break either build or tests on non-UDS platforms

**Comment by etcimon** [comment]
Awesome

**Comment by Calrama** [comment]
https://github.com/Calrama/libasync/commit/1b80b608ac05ee02a015be7fce1aa39798c171c1 implements a UDS listener that seems to work fine. I followed the API for TCP Listener mostly, though I do require for the delegate that received the new UDSConnection to be nothrow (I could not think of any reason to allow exceptions here).

**Comment by Calrama** [comment]
https://github.com/Calrama/libasync/commit/9eb2d2533672e62224447a002c928744da6c4b5a has usage examples for UDS connection and UDS listener

**Comment by Calrama** [comment]
[Whelp](https://github.com/etcimon/libasync/pull/64), it works.

**Comment by Calrama** [comment]
Since the above PR has been merged, I'll close this.

**Comment by etcimon** [comment]
Thanks for the addition. I'm sure a lot of future users will also be thankful the great work
