### ISSUE TITLE
deprecate std.c.linux.socket use core.sys.posix.* instead

### ISSUE THREAD

**Issue by chmike** [etcimon/libasync#56]
When compiling app with libasync I get the following warning
```
../../.dub/packages/libasync-0.7.9/source/libasync/internals/socket_compat.d(57,16): Deprecation: module std.c.linux.socket is deprecated - Import the appropriate core.sys.posix.* modules instead
```

**Comment by etcimon** [comment]
Thanks, and I might remove this module if druntime has implemented every binding properly

**Comment by Calrama** [comment]
@chmike Could you test [this](https://github.com/etcimon/libasync/pull/57)?

**Comment by Calrama** [comment]
Solved for me with https://github.com/etcimon/libasync/commit/7da0a5d62749dc01f28835c81c164ca3b49f47a9.
