### ISSUE TITLE
kqueue: O_NONBLOCK is inherited by accepted sockets?

### ISSUE THREAD

**Issue by Calrama** [etcimon/libasync#63]
From what I can tell from the accept(2) man pages for [OS X](https://developer.apple.com/library/ios/documentation/System/Conceptual/ManPages_iPhoneOS/man2/accept.2.html) and [FreeBSD](https://www.freebsd.org/cgi/man.cgi?query=accept&sektion=2), respective

> creates a new socket with the same properties of socket

and

> allocates a new file descriptor for the socket which inherits the state
     of	the O_NONBLOCK and O_ASYNC properties 

I would think that [this](https://github.com/etcimon/libasync/blob/master/source/libasync/posix.d#L1703) is superfluous?

**Comment by etcimon** [comment]
I hadn't had the chance to test that out, I wanted to stay on the safe side. Would have to try running an app and check the logs to make sure it's not blocking

**Comment by Calrama** [comment]
Hm, I get where you're coming from, I would just add, that *if* they are not blocking on OS X or FreeBSD that would be (according to their manuals) a bug they would need to fix (and we would need to report to them).

**Comment by etcimon** [comment]
Of course, it's very likely to work fine if we remove these 2 lines
