### ISSUE TITLE
dirwatcher example does not work on osx

### ISSUE THREAD

**Issue by gizmomogwai** [etcimon/libasync#83]
it compiles and tells me, to put stuff to the local temp folder, but not output is done if i do so. i am running osx 10.12.6

**Comment by gizmomogwai** [comment]
I checked linux with EPOLL and it just works....

**Comment by etcimon** [comment]
I can't seem to be able to reproduce this, could you give a more exact error?

**Comment by gizmomogwai** [comment]
steps to reproduce on osx:
```
source ~/dlang/dmd-2.082.1/activate.fish
cd ~/tmp
git clone git@github.com:etcimon/libasync.git
cd libasync/examples/dirwatcher
dub build
./dirwatcher
 > Event loop now running. Try saving a file in the temp/ folder!
```
in a separate shell
```
touch ~/tmp/libasync/examples/dirwatcher/temp/test
```

no output on the first shell.
expected output would be something like
file ~/tmp/libasync/examples/dirwatcher/temp/test created.

**Comment by etcimon** [comment]
This has been fixed by now
