### ISSUE TITLE
Compilation error with LDC

### ISSUE THREAD

**Issue by chances** [etcimon/libasync#90]
Tracking https://github.com/etcimon/memutils/issues/19:
> Compilation error with LDC 1.27.0-beta3:
> 
> memutils-1.0.4\memutils\source\memutils\allocators.d(18,8): Error: module `std.exception` import `enforceEx` not found, did you mean template `std.exception.enforce(E : Throwable = Exception) if (is(typeof(new E("", string.init, size_t.init)) : Throwable) || is(typeof(new E(string.init, size_t.init)) : Throwable))`?

Switching to `memutils~master` results in this error in `libasync`:

> ../../../../.dub/packages/libasync-master/libasync/source/libasync/internals/memory.d(17,8): Error: module `std.exception` import `enforceEx` not found, did you mean template `std.exception.enforce(E : Throwable = Exception) if (is(typeof(new E("", string.init, size_t.init)) : Throwable) || is(typeof(new E(string.init, size_t.init)) : Throwable))`?

See #91.
See also #92.

**Comment by cyrusmsk** [comment]
I am not very professional user of GitHub - so I have no idea why your PR is not pass the tests, but it helps me to build and run lighttp with steps below:

- build memutils from ~master
- set add-local with version 1.0.4 in dub (it is very sad that the installation from github and branches are prohibited)
- download chances/libasync branch "fix-signal"
- set add-local with version 8.6.0
- dub build/dub run with dependency lighttp

**Comment by chances** [comment]
Ping @etcimon
